repos:
  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.30.1
    hooks:
      - id: gitleaks
        language_version: system

  - repo: https://github.com/zchee/pre-commit-go
    rev: 6fe12e0f44d8554fc8c6cf66bfdb2c1908f9473a
    hooks:
      - id: gofumpt
      - id: modernize

exclude: '.*/testdata/'
