// Copyright 2026 The pandaemonium Authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package main

import (
	"bytes"
	"flag"
	"fmt"
	"maps"
	"os"
	"slices"
	"strings"

	"github.com/go-json-experiment/json"
	"github.com/google/jsonschema-go/jsonschema"
	gofumpt "mvdan.cc/gofumpt/format"
)

type generator struct {
	definitions         map[string]*jsonschema.Schema
	aliases             map[string]string
	packageName         string
	typeNames           map[string]string
	rawUnions           map[string]struct{}
	rawDecodes          map[string]struct{}
	unionTagger         map[string]struct{}
	pendingUnionTaggers []unionTaggerMethod
	emittedType         map[string]struct{}
}

type structField struct {
	name       string
	typ        string
	tag        string
	unionName  string
	unionShape unionShape
}

type unionShape int

const (
	unionShapeNone unionShape = iota
	unionShapeSingle
	unionShapeOptionalSingle
	unionShapeSlice
)

type unionVariantKind int

const (
	unionVariantObject unionVariantKind = iota
	unionVariantStringEnum
	unionVariantString
	unionVariantArray
)

type unionVariant struct {
	raw          *jsonschema.Schema
	schema       *jsonschema.Schema
	typeName     string
	kind         unionVariantKind
	goType       string
	stringValues []string
	matchKey     string
	matchValue   string
}

type interfaceUnion struct {
	rawVariants []*jsonschema.Schema
	variants    []unionVariant
}

type unionTaggerMethod struct {
	unionName  string
	targetType string
}

const maxHTTPSchemaBytes = 32 << 20

func main() {
	schemaPath := flag.String("schema", "", "path or URL to protocol JSON schema")
	outPath := flag.String("out", "", "path for generated Go file")
	packageName := flag.String("package", "codexappserver", "package name for generated Go file")
	flag.Parse()
	if strings.TrimSpace(*schemaPath) == "" || strings.TrimSpace(*outPath) == "" {
		fatalf("both -schema and -out are required")
	}
	if !validPackageName(*packageName) {
		fatalf("invalid package name %q", *packageName)
	}
	input, err := readSchemaSource(*schemaPath)
	if err != nil {
		fatalf("read schema: %v", err)
	}
	var parsed jsonschema.Schema
	if err := json.Unmarshal(input, &parsed); err != nil {
		fatalf("decode schema: %v", err)
	}
	generated, err := newGenerator(parsed.Definitions).generate(*schemaPath, *packageName)
	if err != nil {
		fatalf("generate: %v", err)
	}
	formatted, err := gofumpt.Source(generated, gofumpt.Options{
		LangVersion: "go1.27",
		ModulePath:  "github.com/zchee/pandaemonium",
		Extra: gofumpt.Extra{
			GroupParams:   true,
			ClotheReturns: true,
		},
	})
	if err != nil {
		fatalf("format generated source: %v\n%s", err, generated)
	}
	if err := os.WriteFile(*outPath, formatted, 0o644); err != nil {
		fatalf("write output: %v", err)
	}
}

func fatalf(format string, args ...any) {
	fmt.Fprintf(os.Stderr, format+"\n", args...)
	os.Exit(1)
}

func newGenerator(definitions map[string]*jsonschema.Schema) *generator {
	return &generator{
		definitions: definitions,
		aliases: map[string]string{
			"AbsolutePathBuf": "string",
			"RequestId":       "string",
		},
		unionTagger: make(map[string]struct{}),
		emittedType: make(map[string]struct{}),
	}
}

func (g *generator) generate(schemaPath, packageName string) ([]byte, error) {
	g.packageName = packageName
	g.typeNames = map[string]string{
		"Config": "ConfigPayload",
		"Thread": "ThreadPayload",
	}
	g.rawUnions = map[string]struct{}{}
	g.rawDecodes = map[string]struct{}{}
	g.pendingUnionTaggers = nil
	var out bytes.Buffer
	fmt.Fprintf(&out, "// Code generated by go generate ./pkg/codex; DO NOT EDIT.\n")
	fmt.Fprintf(&out, "// Source: %s\n\n", schemaSourceLabel(schemaPath))
	fmt.Fprintf(&out, "package %s\n\n", packageName)
	keys := slices.Sorted(maps.Keys(g.definitions))

	needsJSONImport := false
	for _, name := range keys {
		needsJSONImport = needsJSONImport || g.shouldEmitRawCodecWrapper(name, g.definitions[name])
		needsJSONImport = needsJSONImport || g.structNeedsCustomUnmarshal(g.definitions[name])
	}
	if len(keys) > 0 {
		imports := []string{"github.com/go-json-experiment/json/jsontext"}
		if needsJSONImport {
			imports = append(imports, "github.com/go-json-experiment/json")
		}
		slices.Sort(imports)
		if len(imports) == 1 {
			fmt.Fprintf(&out, "import %q\n\n", imports[0])
		} else {
			fmt.Fprintln(&out, "import (")
			for _, importPath := range imports {
				fmt.Fprintf(&out, "\t%q\n", importPath)
			}
			fmt.Fprintln(&out, ")")
			fmt.Fprintln(&out)
		}
	}

	for _, name := range keys {
		if err := g.emitDefinition(&out, name, g.definitions[name]); err != nil {
			return nil, fmt.Errorf("%s: %w", name, err)
		}
		out.WriteByte('\n')
	}
	g.emitPendingUnionTaggers(&out)
	return out.Bytes(), nil
}
