package main

import (
	"bytes"
	"flag"
	"fmt"
	"go/format"
	"os"
	"regexp"
	"slices"
	"sort"
	"strconv"
	"strings"
	"unicode"

	json "github.com/go-json-experiment/json"
	"github.com/google/jsonschema-go/jsonschema"
)

type generator struct {
	definitions map[string]*jsonschema.Schema
	skipped     map[string]bool
	aliases     map[string]string
}

func main() {
	schemaPath := flag.String("schema", "", "path to protocol JSON schema")
	outPath := flag.String("out", "", "path for generated Go file")
	flag.Parse()
	if strings.TrimSpace(*schemaPath) == "" || strings.TrimSpace(*outPath) == "" {
		fatalf("both -schema and -out are required")
	}
	input, err := os.ReadFile(*schemaPath)
	if err != nil {
		fatalf("read schema: %v", err)
	}
	var parsed jsonschema.Schema
	if err := json.Unmarshal(input, &parsed); err != nil {
		fatalf("decode schema: %v", err)
	}
	generated, err := newGenerator(parsed.Definitions).generate(*schemaPath)
	if err != nil {
		fatalf("generate: %v", err)
	}
	formatted, err := format.Source(generated)
	if err != nil {
		fatalf("format generated source: %v\n%s", err, generated)
	}
	if err := os.WriteFile(*outPath, formatted, 0o644); err != nil {
		fatalf("write output: %v", err)
	}
}

func fatalf(format string, args ...any) {
	fmt.Fprintf(os.Stderr, format+"\n", args...)
	os.Exit(1)
}

func newGenerator(definitions map[string]*jsonschema.Schema) *generator {
	return &generator{
		definitions: definitions,
		skipped: map[string]bool{
			"AgentMessageDeltaNotification":       true,
			"Config":                              true,
			"InitializeResponse":                  true,
			"ItemCompletedNotification":           true,
			"Model":                               true,
			"ModelListResponse":                   true,
			"ReasoningEffortOption":               true,
			"ServerInfo":                          true,
			"Thread":                              true,
			"ThreadArchiveResponse":               true,
			"ThreadCompactStartResponse":          true,
			"ThreadForkParams":                    true,
			"ThreadForkResponse":                  true,
			"ThreadItem":                          true,
			"ThreadListParams":                    true,
			"ThreadListResponse":                  true,
			"ThreadReadResponse":                  true,
			"ThreadResumeParams":                  true,
			"ThreadResumeResponse":                true,
			"ThreadSetNameResponse":               true,
			"ThreadStartParams":                   true,
			"ThreadStartResponse":                 true,
			"ThreadTokenUsage":                    true,
			"ThreadTokenUsageUpdatedNotification": true,
			"ThreadUnarchiveResponse":             true,
			"TokenUsageBreakdown":                 true,
			"Turn":                                true,
			"TurnCompletedNotification":           true,
			"TurnError":                           true,
			"TurnInterruptResponse":               true,
			"TurnStartParams":                     true,
			"TurnStartResponse":                   true,
			"TurnStatus":                          true,
			"TurnSteerResponse":                   true,
		},
		aliases: map[string]string{
			"AbsolutePathBuf": "string",
			"RequestId":       "string",
		},
	}
}

func (g *generator) generate(schemaPath string) ([]byte, error) {
	var out bytes.Buffer
	fmt.Fprintf(&out, "// Code generated by go generate ./pkg/codex-app-server; DO NOT EDIT.\n")
	fmt.Fprintf(&out, "// Source: %s\n\n", filepathSlash(schemaPath))
	fmt.Fprintf(&out, "package codexappserver\n\n")
	fmt.Fprintf(&out, "import \"github.com/go-json-experiment/json/jsontext\"\n\n")
	keys := make([]string, 0, len(g.definitions))
	for name := range g.definitions {
		if !g.skipped[name] {
			keys = append(keys, name)
		}
	}
	sort.Strings(keys)
	for _, name := range keys {
		if err := g.emitDefinition(&out, name, g.definitions[name]); err != nil {
			return nil, fmt.Errorf("%s: %w", name, err)
		}
		out.WriteByte('\n')
	}
	return out.Bytes(), nil
}

func filepathSlash(path string) string { return strings.ReplaceAll(path, "\\", "/") }

func (g *generator) emitDefinition(out *bytes.Buffer, name string, def *jsonschema.Schema) error {
	if def == nil {
		return fmt.Errorf("nil schema")
	}
	goName := exportName(name)
	if alias, ok := g.aliases[name]; ok {
		fmt.Fprintf(out, "// %s is generated from the %s schema definition.\n", goName, name)
		fmt.Fprintf(out, "type %s = %s\n", goName, alias)
		return nil
	}
	if enum := stringEnum(def); len(enum) > 0 && includesType(def, "string") {
		fmt.Fprintf(out, "// %s is generated from the %s schema definition.\n", goName, name)
		fmt.Fprintf(out, "type %s string\n\n", goName)
		fmt.Fprintf(out, "const (\n")
		for _, value := range enum {
			constName := goName + exportName(value)
			fmt.Fprintf(out, "\t// %s is the %q %s value.\n", constName, value, goName)
			fmt.Fprintf(out, "\t%s %s = %q\n", constName, goName, value)
		}
		fmt.Fprintf(out, ")\n")
		return nil
	}
	if objectSchema(def) {
		return g.emitStruct(out, goName, name, def)
	}
	goType := g.typeForSchema(def, false)
	fmt.Fprintf(out, "// %s is generated from the %s schema definition.\n", goName, name)
	fmt.Fprintf(out, "type %s = %s\n", goName, goType)
	return nil
}

func (g *generator) emitStruct(out *bytes.Buffer, goName, schemaName string, def *jsonschema.Schema) error {
	fmt.Fprintf(out, "// %s is generated from the %s schema definition.\n", goName, schemaName)
	fmt.Fprintf(out, "type %s struct {\n", goName)
	properties := make([]string, 0, len(def.Properties))
	for name := range def.Properties {
		properties = append(properties, name)
	}
	sort.Strings(properties)
	required := make(map[string]bool, len(def.Required))
	for _, name := range def.Required {
		required[name] = true
	}
	used := map[string]int{}
	for _, jsonName := range properties {
		fieldName := uniqueName(exportName(jsonName), used)
		fieldType := g.typeForSchema(def.Properties[jsonName], !required[jsonName])
		tag := jsonName
		if !required[jsonName] {
			tag += ",omitzero"
		}
		fmt.Fprintf(out, "\t%s %s `json:%q`\n", fieldName, fieldType, tag)
	}
	fmt.Fprintf(out, "}\n")
	return nil
}

func uniqueName(name string, used map[string]int) string {
	if name == "" || name == "_" {
		name = "Value"
	}
	if used[name] == 0 {
		used[name] = 1
		return name
	}
	used[name]++
	return name + strconv.Itoa(used[name])
}

func (g *generator) typeForSchema(def *jsonschema.Schema, optional bool) string {
	if def == nil {
		return "jsontext.Value"
	}
	if def.Ref != "" {
		return pointerIfOptional(g.refType(def.Ref), optional)
	}
	if len(def.AllOf) == 1 {
		return g.typeForSchema(def.AllOf[0], optional)
	}
	if typ, nullable := nullableType(def); typ != "" {
		copy := *def
		copy.Type = typ
		copy.Types = nil
		return g.typeForSchema(&copy, optional || nullable)
	}
	if variant, nullable := nullableVariant(def.AnyOf); variant != nil {
		return g.typeForSchema(variant, optional || nullable)
	}
	if variant, nullable := nullableVariant(def.OneOf); variant != nil {
		return g.typeForSchema(variant, optional || nullable)
	}
	if len(def.AnyOf) > 0 || len(def.OneOf) > 0 || len(def.AllOf) > 0 {
		return "jsontext.Value"
	}
	if def.Items != nil && includesType(def, "array") {
		return "[]" + g.typeForSchema(def.Items, false)
	}
	if includesType(def, "object") {
		if def.AdditionalProperties != nil && len(def.Properties) == 0 {
			return "map[string]" + g.typeForSchema(def.AdditionalProperties, false)
		}
		return "jsontext.Value"
	}
	switch {
	case includesType(def, "string"):
		return pointerIfOptional("string", optional)
	case includesType(def, "boolean"):
		return pointerIfOptional("bool", optional)
	case includesType(def, "integer"):
		return pointerIfOptional(integerType(def.Format), optional)
	case includesType(def, "number"):
		return pointerIfOptional("float64", optional)
	default:
		return "jsontext.Value"
	}
}

func (g *generator) refType(ref string) string {
	name := strings.TrimPrefix(ref, "#/definitions/")
	if alias, ok := g.aliases[name]; ok {
		return alias
	}
	return exportName(name)
}

func pointerIfOptional(name string, optional bool) string {
	if !optional || strings.HasPrefix(name, "[]") || strings.HasPrefix(name, "map[") || name == "any" || name == "jsontext.Value" {
		return name
	}
	if strings.HasPrefix(name, "*") {
		return name
	}
	return "*" + name
}

func integerType(format string) string {
	switch format {
	case "int32", "uint32":
		return strings.TrimPrefix(format, "u")
	case "uint", "uint64":
		return format
	default:
		return "int64"
	}
}

func objectSchema(def *jsonschema.Schema) bool {
	return def != nil && includesType(def, "object") && len(def.Properties) > 0
}

func nullableVariant(variants []*jsonschema.Schema) (*jsonschema.Schema, bool) {
	if len(variants) != 2 {
		return nil, false
	}
	var nonNull *jsonschema.Schema
	nullCount := 0
	for _, variant := range variants {
		if variant != nil && includesType(variant, "null") && variant.Ref == "" && len(variant.Properties) == 0 {
			nullCount++
			continue
		}
		nonNull = variant
	}
	if nullCount == 1 && nonNull != nil {
		return nonNull, true
	}
	return nil, false
}

func nullableType(def *jsonschema.Schema) (string, bool) {
	values := typeStrings(def)
	if !slices.Contains(values, "null") || len(values) != 2 {
		return "", false
	}
	for _, value := range values {
		if value != "null" {
			return value, true
		}
	}
	return "", false
}

func includesType(def *jsonschema.Schema, target string) bool {
	return slices.Contains(typeStrings(def), target)
}

func typeStrings(def *jsonschema.Schema) []string {
	if def == nil {
		return nil
	}
	if def.Type != "" {
		return []string{def.Type}
	}
	return def.Types
}

func stringEnum(def *jsonschema.Schema) []string {
	if def == nil || len(def.Enum) == 0 {
		return nil
	}
	out := make([]string, 0, len(def.Enum))
	for _, value := range def.Enum {
		text, ok := value.(string)
		if !ok {
			return nil
		}
		out = append(out, text)
	}
	return out
}

var nonIdentifier = regexp.MustCompile(`[^A-Za-z0-9]+`)

func exportName(name string) string {
	parts := nonIdentifier.Split(name, -1)
	var out strings.Builder
	for _, part := range parts {
		if part == "" {
			continue
		}
		out.WriteString(exportPart(part))
	}
	result := out.String()
	if result == "" {
		return "Value"
	}
	if first := []rune(result)[0]; unicode.IsDigit(first) {
		return "Value" + result
	}
	if isGoKeyword(result) {
		return result + "Value"
	}
	return result
}

func exportPart(part string) string {
	lower := strings.ToLower(part)
	initialisms := map[string]string{
		"api": "API", "ascii": "ASCII", "cpu": "CPU", "css": "CSS", "dns": "DNS", "eof": "EOF",
		"gpu": "GPU", "html": "HTML", "http": "HTTP", "https": "HTTPS", "id": "ID", "ip": "IP",
		"json": "JSON", "lsp": "LSP", "mcp": "MCP", "oauth": "OAuth", "rpc": "RPC", "sdp": "SDP",
		"sdk": "SDK", "sql": "SQL", "ssh": "SSH", "tcp": "TCP", "tls": "TLS", "tty": "TTY",
		"ui": "UI", "uid": "UID", "uri": "URI", "url": "URL", "utf8": "UTF8", "uuid": "UUID",
		"vm": "VM", "xml": "XML",
	}
	if value, ok := initialisms[lower]; ok {
		return value
	}
	runes := []rune(part)
	if len(runes) == 0 {
		return ""
	}
	if hasUpperAfterFirst(runes) {
		runes[0] = unicode.ToUpper(runes[0])
		return normalizeInitialisms(string(runes))
	}
	for i := range runes {
		runes[i] = unicode.ToLower(runes[i])
	}
	runes[0] = unicode.ToUpper(runes[0])
	return string(runes)
}

func hasUpperAfterFirst(runes []rune) bool {
	for _, r := range runes[1:] {
		if unicode.IsUpper(r) {
			return true
		}
	}
	return false
}

func normalizeInitialisms(name string) string {
	replacements := []struct{ old, new string }{
		{"Api", "API"},
		{"Ascii", "ASCII"},
		{"Cpu", "CPU"},
		{"Css", "CSS"},
		{"Dns", "DNS"},
		{"Eof", "EOF"},
		{"Gpu", "GPU"},
		{"Html", "HTML"},
		{"Https", "HTTPS"},
		{"Http", "HTTP"},
		{"Json", "JSON"},
		{"Lsp", "LSP"},
		{"Mcp", "MCP"},
		{"Oauth", "OAuth"},
		{"Rpc", "RPC"},
		{"Sdp", "SDP"},
		{"Sdk", "SDK"},
		{"Sql", "SQL"},
		{"Ssh", "SSH"},
		{"Tcp", "TCP"},
		{"Tls", "TLS"},
		{"Tty", "TTY"},
		{"Uid", "UID"},
		{"Uri", "URI"},
		{"Url", "URL"},
		{"Utf8", "UTF8"},
		{"Uuid", "UUID"},
		{"Xml", "XML"},
		{"Id", "ID"},
		{"Ui", "UI"},
	}
	for _, replacement := range replacements {
		name = strings.ReplaceAll(name, replacement.old, replacement.new)
	}
	return name
}

func isGoKeyword(name string) bool {
	switch name {
	case "Break", "Default", "Func", "Interface", "Select", "Case", "Defer", "Go", "Map", "Struct", "Chan", "Else", "Goto", "Package", "Switch", "Const", "Fallthrough", "If", "Range", "Type", "Continue", "For", "Import", "Return", "Var":
		return true
	default:
		return false
	}
}
